# Generated by Django 4.0.4 on 2022-06-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Баланс автосалона'),
        ),
    ]
