# Generated by Django 4.0.5 on 2022-06-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_customer_balance_alter_showroom_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.car'),
        ),
        migrations.AddField(
            model_name='customerhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='showroomhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.customer')),
            ],
        ),
    ]
