# Generated by Django 4.0.4 on 2022-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosalon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год выпуска'),
        ),
    ]
