# Generated by Django 4.0.6 on 2022-07-13 12:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("provider", "0001_initial"),
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Showroom name"),
                ),
                (
                    "location",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Location"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Showroom balance",
                    ),
                ),
                ("query", models.JSONField(blank=True)),
            ],
            options={
                "verbose_name": "Showroom",
                "verbose_name_plural": "Showrooms",
                "ordering": ["-created_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShowroomHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "car",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="car.car",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="provider.provider",
                    ),
                ),
                (
                    "showroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showroom.showroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShowroomDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField()),
                ("percent", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "cars",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="car.car",
                    ),
                ),
                (
                    "showroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showroom.showroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="showroom",
            name="cars",
            field=models.ManyToManyField(
                blank=True, through="showroom.ShowroomHistory", to="car.car"
            ),
        ),
        migrations.AddField(
            model_name="showroom",
            name="customers",
            field=models.ManyToManyField(blank=True, to="customer.customer"),
        ),
    ]
