# Generated by Django 4.0.6 on 2022-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("provider", "0001_initial"),
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="showrooms",
            field=models.ManyToManyField(blank=True, to="showroom.showroom"),
        ),
    ]
